type: "BCDDPGAgent"
hyper_params:
  gamma: 0.99
  tau: 0.001
  buffer_size: 100000
  batch_size: 512
  initial_random_action: 10000
  multiple_update: 1  # multiple learning updates
  gradient_clip_ac: 0.5
  gradient_clip_cr: 0.5
  # BC
  demo_batch_size: 64
  lambda1: 0.001
  demo_path: "data/lunarlander_continuous_demo.pkl"
  # HER
  use_her: False
  her:
    type: LunarLanderContinuousHER
  success_score: 250.0
  desired_states_from_demo: True

learner_cfg:
  type: "BCDDPGLearner"
  backbone:
    actor:
    critic:
    shared_actor_critic:
  head:
    actor:
      type: "MLP"
      configs: 
        hidden_sizes: [256, 256]
        output_activation: "tanh"
    critic:
      type: "MLP"
      configs:
        hidden_sizes: [256, 256]
        output_size: 1
        output_activation: "identity"
  optim_cfg:
    lr_actor: 0.0001
    lr_critic: 0.001
    weight_decay: 0.0001

noise_cfg:
  ou_noise_theta: 0.0
  ou_noise_sigma: 0.0
