type: "GAILPPOAgent"
hyper_params:
  gamma: 0.99
  tau: 0.95
  batch_size: 128
  max_epsilon: 0.2
  min_epsilon: 0.2
  epsilon_decay_period: 1500
  w_value: 1.0
  w_entropy: 0.001
  gradient_clip_ac: 1.0
  gradient_clip_cr: 0.5
  epoch: 10
  rollout_len: 2048
  n_workers: 4
  use_clipped_value_loss: False
  standardize_advantage: False
  is_discrete: False
  # gail
  gail_reward_weight: 0.0
  demo_path: "data/lunarlander_continuous_demo.pkl"

learner_cfg:
  type: "GAILPPOLearner"
  backbone:
    actor:
    critic:
    discriminator: 
  head:
    actor:
      type: "GaussianDist"
      configs: 
        hidden_sizes: [256, 256]
        output_activation: "tanh"
    critic:
      type: "MLP"
      configs:
        hidden_sizes: [256, 256]
        output_size: 1
        output_activation: "identity"
    discriminator:
      type: "MLP"
      configs:
        hidden_sizes: [256, 256]
        output_size: 1
        output_activation: "identity"
  optim_cfg:
    lr_actor: 0.0003
    lr_critic: 0.001
    lr_discriminator: 0.0003
    weight_decay: 0.0
