type: "PPOAgent"
hyper_params:
  gamma: 0.99
  tau: 0.95
  batch_size: 32
  max_epsilon: 0.2
  min_epsilon: 0.2
  epsilon_decay_period: 1500
  w_value: 1.0
  w_entropy: 0.001
  gradient_clip_ac: 1.0
  gradient_clip_cr: 0.5
  epoch: 16
  rollout_len: 256
  n_workers: 12
  use_clipped_value_loss: True
  standardize_advantage: True
  is_discrete: False

learner_cfg:
  type: "PPOLearner"
  backbone:
    actor:
    critic:
  head:
    actor:
      type: "GaussianDist"
      configs: 
        hidden_sizes: [256, 256]
        output_activation: "tanh"
    critic:
      type: "MLP"
      configs:
        hidden_sizes: [256, 256]
        output_size: 1
        output_activation: "identity"
  optim_cfg:
    lr_actor: 0.0003
    lr_critic: 0.001
    weight_decay: 0.0
