type: ACERAgent
hyper_params:
 gamma: 0.98
 c: 1
 buffer_size: 5000
 n_rollout: 10
 replay_ratio: 16
 start_from: 100
 gradient_clip: 10
 tau: 0.005

learner_cfg:
 type: ACERLearner
 backbone:
  actor:
  critic:
  shared_actor_critic:
 head:
  actor:
   type: MLP
   configs:
    hidden_sizes: [256, 256]
    output_activation: identity
  critic:
   type: MLP
   configs:
    hidden_sizes: [256, 256]
    output_activation: identity
 optim_cfg:
  lr: 0.0002
  weight_decay: 0.0
  adam_eps: 0.00000001
 trust_region:
  use_trust_region: true
  delta: 1
