type: ACERAgent
hyper_params:
 gamma: 0.99
 c: 10
 buffer_size: 20000
 n_rollout: 20
 replay_ratio: 0
 start_from: 1000
 gradient_clip: 10
 tau: 0.01

learner_cfg:
 type: ACERLearner
 backbone:
  actor:
  critic:
  shared_actor_critic:
    type: "CNN"
    configs:
      input_sizes: [4, 32, 64]
      output_sizes: [32, 64, 64]
      kernel_sizes: [8, 4, 3]
      strides: [4, 2, 1]
      paddings: [1, 0, 0]
 head:
  actor:
    type: MLP
    configs: 
      hidden_sizes: [512, 512]
      output_activation: "identity"
  critic:
    type: "MLP"
    configs:
      hidden_sizes: [512]
      output_size: 1
      output_activation: "identity"
 optim_cfg:
  lr: 0.0001
  weight_decay: 0.0
  adam_eps: 0.0000001
 trust_region:
  use_trust_region: true
  delta: 1
